### ISSUE TITLE
error: redefinition of ‘struct sha256_state’

### ISSUE THREAD

**Issue by hainahouwei** [McMCCRU/rtl8188gu#10]
`rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /home/simon/rtl8188gu/include/osdep_service_linux.h:48,
                 from /home/simon/rtl8188gu/include/osdep_service.h:50,
                 from /home/simon/rtl8188gu/include/drv_types.h:27,
                 from /home/simon/rtl8188gu/core/rtw_cmd.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:286: /home/simon/rtl8188gu/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1783: /home/simon/rtl8188gu] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-48-generic'
make: *** [Makefile:2287: modules] Error 2
simon@simon-VirtualBox:~/rtl8188gu$ ^C`

**Comment by McMCCRU** [comment]
https://github.com/McMCCRU/rtl8188gu/issues/7
