### ISSUE TITLE
Wifi Adaper not found after Update

### ISSUE THREAD

**Issue by RaghuManickam** [McMCCRU/rtl8188gu#13]
Hi ,

This works fine but . when i update my ubuntu .

The wifi adapter is not found again . Please let me know is there a way to fix this

Kernal Version 5.4.0-73

**Comment by McMCCRU** [comment]
Hi! I cannot answer questions related to the features of different Linux distributions...

**Comment by RaghuManickam** [comment]
This got resolved automatically after shutdown and start again
