### ISSUE TITLE
Module not working on kernel 5.11 (working until 5.8)

### ISSUE THREAD

**Issue by KierPrev** [McMCCRU/rtl8188gu#15]
Hi, now I'm booting with 5.8 for making it work, but if I update to the new 5.11 kernel, it builds, makes and installs, but when I do modprobe, the wired network is showing no SSIDs, also my system glitches, sudo don't work anymore, and I have to force restart.

Any solution to make it work for 5.11?  I'm on Ubuntu, pretty much clean installation.
I already installed the 5.11 kernel extras, but no luck.

Thanks!

**Comment by woshidaxia123** [comment]
same problem as yours

**Comment by McMCCRU** [comment]
Hi all! I fixed this problem.
https://github.com/McMCCRU/rtl8188gu/commit/16bc67b00ec8940a72033dd5b5a495a82145df6a

**Comment by KierPrev** [comment]
Totally amazing!
Now it works even on the last kernel 5.14.16-arch1-1!

Many thanks!
