### ISSUE TITLE
kali-linux can't install this driver.

### ISSUE THREAD

**Issue by Simple2ich4n** [McMCCRU/rtl8188gu#20]
i install to kali  5.14.0-kali2-amd64 #1 SMP Debian 5.14.9-2kali1 (2021-10-04) x86_64 GNU/Linux , 
i check the header and make && make install ,but  the network will freeze after starting the network  in the vm。
i type to any network command ，all will get stuck and fail , PLS help me...  0_0

this is my network card: [https://service.mercurycom.com.cn/product-242-2.html](url)

└─# lsusb                                                                                                                                           
Bus 003 Device 005: ID 0bda:b711 Realtek Semiconductor Corp. RTL8188GU 802.11n WLAN Adapter (After Modeswitch)

└─# dmesg
[  484.375159] Call Trace:
[  484.375163]  __schedule+0x2f0/0x910
[  484.375168]  schedule+0x44/0xa0
[  484.375170]  schedule_preempt_disabled+0xa/0x10
[  484.375171]  __mutex_lock.constprop.0+0x28a/0x440
[  484.375172]  addrconf_verify_work+0xa/0x20
[  484.375175]  process_one_work+0x1ec/0x390
[  484.375179]  worker_thread+0x53/0x3e0
[  484.375180]  ? process_one_work+0x390/0x390
[  484.375182]  kthread+0x127/0x150
[  484.375184]  ? set_kthread_struct+0x40/0x40
[  484.375185]  ret_from_fork+0x22/0x30
[ 1052.592534] e1000: eth0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: None
[ 1053.436839] usb 3-2.1: USB disconnect, device number 5

**Comment by McMCCRU** [comment]
Hi! I can’t help, I don’t use kali linux.
