### ISSUE TITLE
"NetworkManager needs to be running"

### ISSUE THREAD

**Issue by HooG1** [McMCCRU/rtl8188gu#21]
Hi everyone. 
Sorry for my noob question I'm really new with Linux OS.
My machine runs on Ubuntu 20.04.3 and I intended to use Comfast CFWU815N USB WiFi LAN card. Upon checking via the internet, I found out that the chipset is Realtek 8188gu. So, from there, I stumbled upon this site. 
I finished installing the driver by inserting the following commands in the terminal:

     git clone https://github.com/McMCCRU/rtl8188gu

     cd rtl8188gu

     make

     sudo make install
     
Then, I rebooted my machine, and still couldn't get into the internet. Computer freezes, couldn't start the browser, and the message I get in the browser setting is in the photo attached. 

![1635869989593](https://user-images.githubusercontent.com/93607810/139908697-6ad32bb3-3098-49e0-bd07-4e01bcaf51c9.jpg)

I would appreciate if anyone could assist me. 

Many thanks

**Comment by KierPrev** [comment]
This issue is solved then, and should be closed as solved.

**Comment by HooG1** [comment]
> This issue is solved then, and should be closed as solved.

Hi, so I just reinstall the driver by inserting the same command as I did previously?

**Comment by KierPrev** [comment]
Yes. Delete your old downloaded driver, and clone the updated one.
