### ISSUE TITLE
Error while compiling on hardened Arch Linux

### ISSUE THREAD

**Issue by LeSpodify** [McMCCRU/rtl8188gu#26]
[spodi@spodi rtl8188gu]$ make
/bin/sh: line 1: bc: command not found
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.14.18-hardened1-1-hardened/build M=/home/spodi/rtl8188gu  modules
make[1]: *** /lib/modules/5.14.18-hardened1-1-hardened/build: No such file or directory.  Stop.
make: *** [Makefile:1894: modules] Error 2
[spodi@spodi rtl8188gu]$

**Comment by McMCCRU** [comment]
Hi! Set path where you have the kernel sources in Makefile or run as KSRC=/bla/bla/linux-5.14.18 make
Is not problem!
