### ISSUE TITLE
Add support for TOTOLINK N150UA-B

### ISSUE THREAD

**Issue by a5a5aa555oo** [McMCCRU/rtl8188gu#27]
Hi

First, thanks for maintaining this driver.
I have a TOTOLINK N150UA-B usb wireless dongle.
It has a RTL8188GU chip inside, too.
but its VID/PID is 0BDA:2005.
After adding the following line to  the file "os_dep/linux/usb_intf.c"
my usb dongle works now.
so I wonder if you can add support for this dongle.
Thanks again!.

`{USB_DEVICE_AND_INTERFACE_INFO(USB_VENDER_ID_REALTEK, 0x2005, 0xff, 0xff, 0xff), .driver_info = RTL8710B},`

lsusb: (before/after mode switching)
Bus 002 Device 024: ID 0bda:1a2b Realtek Semiconductor Corp. RTL8188GU 802.11n WLAN Adapter (Driver CDROM Mode)
Bus 002 Device 010: ID 0bda:2005 Realtek Semiconductor Corp. 802.11n WLAN Adapter

**Comment by McMCCRU** [comment]
Hi! OK, is added this https://github.com/McMCCRU/rtl8188gu/commit/94e8f154ddac8de9d8a82c479f1c4bcdb733894d

**Comment by a5a5aa555oo** [comment]
Thanks a lot! :)
