### ISSUE TITLE
ubuntu18.04 安装之后也不能开启wifi

### ISSUE THREAD

**Issue by Julius-ZCJ** [McMCCRU/rtl8188gu#28]
大佬您好：
        我下载这个驱动安装之后没反应，不知道是啥问题，求大佬指点。

系统：ubuntu18.04
内核：5.4.0
我首先查看了我的usb无线网卡的型号，结果如图：
![微信图片_20211214110855](https://user-images.githubusercontent.com/42171296/145927029-f3af538c-fbcb-44b5-bc58-383ef86ee3ea.jpg)

然后通过搜索得到，我需要安装的网卡驱动为：
![微信图片_20211214111545](https://user-images.githubusercontent.com/42171296/145927067-04de7196-503d-43ad-9b9d-843dc7c9debd.png)

通过搜索在GitHub上找到大佬发布的驱动
make和sudo make install 都没有报错，如下图所示，这是我第二次安装之后的结果：
![微信图片_20211214110439](https://user-images.githubusercontent.com/42171296/145927093-e900876f-859c-406c-b03b-4fbe96105b3d.jpg)

我以为已经安装成功了，然后重启电脑，发现还是不可以使用无线WiFi，如下图：
![微信图片_20211214111825](https://user-images.githubusercontent.com/42171296/145927109-d24989af-d57d-4e63-bb73-74c850afb945.jpg)

想问下大佬，我这是哪里操作错误了，请大佬指教

**Comment by supertsy5** [comment]
去看一下/dev目录，找一找有没有/dev/sr0或者类似的设备（这个是用于在Windows上安装驱动的）
如果有，eject

**Comment by supertsy5** [comment]
然后你的设备型号应该会变成0bda:b711

**Comment by joeybronzoni** [comment]
I can't read any of these comments...
