### ISSUE TITLE
sources for USB 0bda:1a2b

### ISSUE THREAD

**Issue by sacarde** [McMCCRU/rtl8188gu#29]
hi,
   is this source working for USB 0bda:1a2b ?

thank you

**Comment by McMCCRU** [comment]
Hi! It's device in CDROM mode, you need switch in WiFi mode!
Use commands:
sudo eject /dev/cdrom0 (or /dev/sr0, etc)
or
sudo usb_modeswitch -KW -v 0bda -p 1a2b

**Comment by sacarde** [comment]
but is a problem if I dont view in command:

modinfo 8188gu

any "alias" with "1A2B" ?

**Comment by McMCCRU** [comment]
PID 1A2B this Realtek CDROM with drivers for install in Windows! You need to change this PID for Wi-Fi mode to B711 or other using those commands.

**Comment by sacarde** [comment]
but running: sudo usb_modeswitch -KW -v 0bda -p 1a2b

http://sacarde.altervista.org/np/aa11

dont change anythings

**Comment by McMCCRU** [comment]
If my commands to switch to Wi-Fi mode did not help you, then I cannot help you with anything. Try google search...
