### ISSUE TITLE
insmod:ERROR Problem!!!

### ISSUE THREAD

**Issue by guoerba** [McMCCRU/rtl8188gu#32]
I cover a insmod problem:

insmod 8188gu.ko
insmod: ERROR: could not insert module 8188gu.ko: Unknown symbol in module

**Comment by wandercn** [comment]
我也遇到8188gu型号驱动问题，自己找资料整理了安装指南.我在Raspberry pi 和 ubuntu 20.0.4都安装成功了。deepin也应该可以。解决了您的问题帮忙点个星星

https://github.com/wandercn/RTL8188GU
