### ISSUE TITLE
Cannot build it in archlinux 5.17

### ISSUE THREAD

**Issue by namilantu** [McMCCRU/rtl8188gu#35]

**Comment by namilantu** [comment]
Cannot build it in archlinux 5.17

**Comment by namilantu** [comment]
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/efuse/rtw_efuse.c: 在函数‘rtw_efuse_analyze’中:
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/efuse/rtw_efuse.c:713:17: 警告：this ‘if’ clause does not guard... [-Wmisleading-indentation]
  713 |                 if (i % 16 == 0)
      |                 ^~
In file included from /var/lib/dkms/rtl8188gu/r14.23b04ff/build/include/drv_types.h:60,
                 from /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/efuse/rtw_efuse.c:17:
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/include/rtw_debug.h:292:9: 附注：...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  292 |         do {\
      |         ^~
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/efuse/rtw_efuse.c:715:25: 附注：in expansion of macro ‘_RTW_PRINT_SEL’
  715 |                         _RTW_PRINT_SEL(RTW_DBGDUMP, "%02X%s"
      |                         ^~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.o
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c: 在函数‘thread_exit’中:
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c:1210:9: 错误：隐式声明函数‘complete_and_exit’ [-Werror=implicit-function-declaration]
 1210 |         complete_and_exit(comp, 0);
      |         ^~~~~~~~~~~~~~~~~
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c: 在函数‘rtw_change_ifname’中:
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c:2375:28: 警告：passing argument 1 of ‘_rtw_memcpy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 2375 |         _rtw_memcpy(pnetdev->dev_addr, adapter_mac_addr(padapter), ETH_ALEN);
      |                     ~~~~~~~^~~~~~~~~~
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c:915:24: 附注：需要类型‘void *’，但实参的类型为‘const unsigned char *’
  915 | void _rtw_memcpy(void *dst, const void *src, u32 sz)
      |                  ~~~~~~^~~
cc1：有些警告被当作是错误
make[2]: *** [scripts/Makefile.build:288：/var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.o] 错误 1
make[1]: *** [Makefile:1831：/var/lib/dkms/rtl8188gu/r14.23b04ff/build] 错误 2
make[1]: 离开目录“/usr/lib/modules/5.17.3-arch1-1/build”
make: *** [Makefile:1895：modules] 错误 2

**Comment by Bounteous17** [comment]
Same issue trying to run that on **_Archlinux_** with kernel [5.17-zen](https://archlinux.org/packages/extra/x86_64/linux-zen/)

**Comment by McMCCRU** [comment]
Hi! Fixed.
https://github.com/McMCCRU/rtl8188gu/commit/a7b49773340f1f9e6fd96fcff00e8edb1fb1e30f
