### ISSUE TITLE
Why this driver can not use after installed some days?

### ISSUE THREAD

**Issue by ultwcz** [McMCCRU/rtl8188gu#37]
hi, when i installed this driver,it can use normally,but after some days(about two weeks),my computer can't find wifi adapter.
i should recompile and reinstall driver to solver this problem.

linux:Ubuntu 18.04
kernel:5.4.110

thanks

**Comment by McMCCRU** [comment]
I can't give advice on different linux distributions, it's not a driver problem. Use DKMS, this should solve your problem.

**Comment by ultwcz** [comment]
> I can't give advice on different linux distributions, it's not a driver problem. Use DKMS, this should solve your problem.

yes,it's my problem,because my linux host $(uname -r) is changed,thanks you.
