### ISSUE TITLE
No rule to make target 'arch/armv7l/Makefile'.  Stop.

### ISSUE THREAD

**Issue by PanQyB** [McMCCRU/rtl8188gu#38]
Hi. I have problem with installation driver.

OrangePi PC
OS: Armbian (22.05.0-trunk.0004) armv7l
Kernel: 5.15.25-sunxi

Headers installed via armbian-config but have that problem at console

_make[1]: Entering directory '/usr/src/linux-headers-5.15.25-sunxi'
Makefile:701: arch/armv7l/Makefile: No such file or directory
make[1]: *** No rule to make target 'arch/armv7l/Makefile'.  Stop.
make[1]: Leaving directory '/usr/src/linux-headers-5.15.25-sunxi'
make: *** [Makefile:1895: modules] Error 2_

please help me

**Comment by McMCCRU** [comment]
It's not a driver build problem, it's a problem with your build system! Contact your community for help.
