### ISSUE TITLE
Cannot build it in archlinux 5.18.1-arch-1

### ISSUE THREAD

**Issue by namilantu** [McMCCRU/rtl8188gu#39]
Hello,
I'm sorry to disturb you, but it fails to build in archlinux 5.18.1-arch-1,
the error is as follows:
DKMS make.log for rtl8188gu-r14.23b04ff for kernel 5.18.1-arch1-1 (x86_64)
2022年 06月 01日 星期三 10:29:44 CST
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.18.1-arch1-1/build M=/var/lib/dkms/rtl8188gu/r14.23b04ff/build  modules
make[1]: 进入目录“/usr/lib/modules/5.18.1-arch1-1/build”
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_io.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_ieee80211.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_mlme.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_mlme_ext.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_mi.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_wlan_util.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_vht.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_pwrctrl.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_rf.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_recv.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_sta_mgt.o
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_sta_mgt.c: 在函数‘rtw_mfree_stainfo’中:
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_sta_mgt.c:352:25: 警告：the comparison will always evaluate as ‘true’ for the address of ‘lock’ will never be NULL [-Waddress]
  352 |         if (&psta->lock != NULL)
      |                         ^~
In file included from /var/lib/dkms/rtl8188gu/r14.23b04ff/build/include/drv_types.h:106,
                 from /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_sta_mgt.c:17:
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/include/sta_info.h:229:17: 附注：‘lock’在此声明
  229 |         _lock   lock;
      |                 ^~~~
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_ap.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_xmit.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_p2p.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_rson.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_tdls.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_br_ext.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_iol.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_sreset.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_btcoex_wifionly.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_btcoex.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_beamforming.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_odm.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/efuse/rtw_efuse.o
  CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.o
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c: 在函数‘isFileReadable’中:
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c:2089:9: 错误：未知的类型名‘mm_segment_t’
 2089 |         mm_segment_t oldfs;
      |         ^~~~~~~~~~~~
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c: 在函数‘retriveFromFile’中:
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c:2129:9: 错误：未知的类型名‘mm_segment_t’
 2129 |         mm_segment_t oldfs;
      |         ^~~~~~~~~~~~
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c: 在函数‘storeToFile’中:
/var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c:2168:9: 错误：未知的类型名‘mm_segment_t’
 2168 |         mm_segment_t oldfs;
      |         ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:288：/var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.o] 错误 1
make[1]: *** [Makefile:1834：/var/lib/dkms/rtl8188gu/r14.23b04ff/build] 错误 2
make[1]: 离开目录“/usr/lib/modules/5.18.1-arch1-1/build”
make: *** [Makefile:1896：modules] 错误 2

**Comment by McMCCRU** [comment]
https://github.com/McMCCRU/rtl8188gu/commit/b24e8a3b06cbf47ba8157af69a18f20d5ede7126
fixed
