### ISSUE TITLE
Cannot build on arm linux

### ISSUE THREAD

**Issue by lemongad** [McMCCRU/rtl8188gu#44]
when try to make:
![Screenshot_20220814_153847_com sonelli juicessh](https://user-images.githubusercontent.com/104255899/184527341-e6c37bbe-2a59-4ff2-ae0b-5d83e7cd9639.png)

**Comment by lemongad** [comment]
please help me ,thanks

**Comment by McMCCRU** [comment]
It's not a driver build problem, it's a problem with your build system! Contact your community for help.  Most likely, you need install the kernel sources/headers...
