### ISSUE TITLE
RTL8188GU firmware?

### ISSUE THREAD

**Issue by a5a5aa555oo** [McMCCRU/rtl8188gu#56]
Hi,

Sorry that i am going to ask a question not  completely related to this repo.
I found there is a new kernel patch for the RTL8188GU WNIC,
so I built the kernel from the kernel git tree with this patch.
but it needs a firmware file called "rtl8710bufw.bin" to work properly.
How can i find or make this firmware file?
Thanks.

Patch
https://patchwork.kernel.org/project/linux-wireless/patch/4edbe29f-00b9-8eef-9789-20bed0b141e2@gmail.com/

dmesg
[   11.332144] usb 1-3: RTL8710BU rev A (unknown) romver 2, 1T1R, TX queues 3, WiFi=1, BT=0, GPS=0, HI PA=0
[   11.332151] usb 1-3: RTL8710BU MAC: f4:28:53:1b:89:f8
[   11.332157] usb 1-3: rtl8xxxu: Loading firmware rtlwifi/rtl8710bufw.bin
[   11.362090] usb 1-3: Direct firmware load for rtlwifi/rtl8710bufw.bin failed with error -2
[   11.362104] usb 1-3: request_firmware(rtlwifi/rtl8710bufw.bin) failed
[   11.362109] usb 1-3: Fatal - failed to load firmware
[   11.362154] rtl8xxxu: probe of 1-3:1.0 failed with error -11

**Comment by dubhater** [comment]
The firmware you need for "(unknown) romver 2" is in [this patch](https://github.com/McMCCRU/rtl8188gu/files/10832134/8188-umc.txt). It comes from the Windows driver. You can convert the C array into a binary file using xxd or something like that.

I think if you wait a few more days you will be able to obtain the firmware from [the normal place](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/rtlwifi).

**Comment by a5a5aa555oo** [comment]
Thank you so much!
I will try it later.

**Comment by a5a5aa555oo** [comment]
Is the link of the patch correct?
I just see a dmesg log.

I create a rtl8710bufw.bin from hal8710b_fw.c 
but wifi dongle still doesn't work as expect.

[   91.087739] usb 5-3: This Realtek USB WiFi dongle (0x0bda:0x2005) is untested!
[   91.087747] usb 5-3: Please report results to Jes.Sorensen@gmail.com
[   91.139801] usb 5-3: Dumping efuse for RTL8710BU (0x200 bytes):
[   91.139808] 00000000: 95 81 c2 16 ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139810] 00000010: ff ff ff ff ff ff ff ff e0 00 00 02 ff ff ff ff  ................
[   91.139812] 00000020: 25 25 25 25 25 25 24 24 24 24 24 02 ff ff ff ff  %%%%%%$$$$$.....
[   91.139814] 00000030: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139815] 00000040: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139817] 00000050: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139818] 00000060: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139819] 00000070: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139820] 00000080: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139822] 00000090: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139823] 000000a0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139824] 000000b0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139825] 000000c0: ff ff ff ff ff ff ff ff 20 2f 19 05 00 00 00 ff  ........ /......
[   91.139827] 000000d0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139828] 000000e0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139829] 000000f0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139830] 00000100: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139831] 00000110: ff ff ff ff ff ff ff ff ff ff f4 28 53 1b 89 f8  ...........(S...
[   91.139833] 00000120: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139834] 00000130: ff 01 00 10 00 ff 00 ff 10 00 ff ff ff ff ff ff  ................
[   91.139835] 00000140: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139837] 00000150: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139838] 00000160: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139839] 00000170: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139840] 00000180: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139841] 00000190: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139843] 000001a0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139844] 000001b0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139845] 000001c0: da 0b 05 20 ff ff ff ff ff ff ff ff 03 98 ff ff  ... ............
[   91.139846] 000001d0: ff ff 00 00 ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139848] 000001e0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139849] 000001f0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[   91.139850] usb 5-3: RTL8710BU rev A (unknown) romver 2, 1T1R, TX queues 3, WiFi=1, BT=0, GPS=0, HI PA=0
[   91.139854] usb 5-3: RTL8710BU MAC: f4:28:53:1b:89:f8
[   91.139857] usb 5-3: rtl8xxxu: Loading firmware rtlwifi/rtl8710bufw.bin
[   91.154045] usb 5-3: Firmware revision 16.0 (signature 0x10b1)
[   92.671202] usb 5-3: Firmware failed to start
[   92.671225] rtl8xxxu: probe of 5-3:1.0 failed with error -11
[   92.671299] usbcore: registered new interface driver rtl8xxxu

**Comment by a5a5aa555oo** [comment]
Oh! It works now!
NO slow upload speed anymore.
Hope this new patch getting better and  be merged into kernel mainline soon.
Thank you, @dubhater and Bitterblue Smith!

https://pastebin.com/Efm4VxHG

**Comment by dubhater** [comment]
Thanks for testing.

**Comment by a5a5aa555oo** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/rtlwifi

The firmware files for RTL8188GU are in the kernel.org repo now.
