### ISSUE TITLE
Cannot build on Manjaro 6.1.12

### ISSUE THREAD

**Issue by br0nde** [McMCCRU/rtl8188gu#57]
This is the output of the `make` command

> make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/6.1.12-1-MANJARO/build M=/var/lib/dkms/rtl8188gu/r14.23b04ff/build  modules
> make[1]: вход в каталог «/usr/lib/modules/6.1.12-1-MANJARO/build»
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_cmd.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_security.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_debug.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_io.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_ioctl_query.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_ioctl_set.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_ieee80211.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_mlme.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_mlme_ext.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_mi.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_wlan_util.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_vht.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_pwrctrl.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_rf.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_recv.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_sta_mgt.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_ap.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_xmit.o
> /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_sta_mgt.c: В функции «rtw_mfree_stainfo»:
> /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_sta_mgt.c:352:25: предупреждение: the comparison will always evaluate as «true» for the address of «lock» will never be NULL [-Waddress]
>   352 |         if (&psta->lock != NULL)
>       |                         ^~
> In file included from /var/lib/dkms/rtl8188gu/r14.23b04ff/build/include/drv_types.h:106,
>                  from /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_sta_mgt.c:17:
> /var/lib/dkms/rtl8188gu/r14.23b04ff/build/include/sta_info.h:229:17: замечание: «lock» объявлено здесь
>   229 |         _lock   lock;
>       |                 ^~~~
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_p2p.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_rson.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_tdls.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_br_ext.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_iol.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_sreset.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_btcoex_wifionly.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_btcoex.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_beamforming.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/rtw_odm.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/core/efuse/rtw_efuse.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/linux/os_intfs.o
>   CC [M]  /var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/linux/usb_intf.o
> /var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c: В функции «isFileReadable»:
> /var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c:2089:9: ошибка: неизвестное имя типа «mm_segment_t»
>  2089 |         mm_segment_t oldfs;
>       |         ^~~~~~~~~~~~
> /var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c: В функции «retriveFromFile»:
> /var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c:2129:9: ошибка: неизвестное имя типа «mm_segment_t»
>  2129 |         mm_segment_t oldfs;
>       |         ^~~~~~~~~~~~
> /var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c: В функции «storeToFile»:
> /var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.c:2168:9: ошибка: неизвестное имя типа «mm_segment_t»
>  2168 |         mm_segment_t oldfs;
>       |         ^~~~~~~~~~~~
> make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/rtl8188gu/r14.23b04ff/build/os_dep/osdep_service.o] Error 1
> make[2]: *** Ожидание завершения заданий…
> make[1]: *** [Makefile:2005: /var/lib/dkms/rtl8188gu/r14.23b04ff/build] Error 2
> make[1]: выход из каталога «/usr/lib/modules/6.1.12-1-MANJARO/build»
> make: *** [Makefile:1896: modules] Error 2

**Comment by hrimfaxi** [comment]
Try revert commit c98b373c06c0f39c78de64253bdb9718eb4e30db

**Comment by a5a5aa555oo** [comment]
Your  source code is not from this repo.
You should ask for help from the ACTUAL maintainer of your code.
The code in this repo has no issue you mentioned.

**Comment by br0nde** [comment]
Thanks! Driver was compiled and installed success. All work!

**Comment by a5a5aa555oo** [comment]
You can try this if you are interested. Linux kernel 6.0+ supported.

https://github.com/lwfinger/rtl8xxxu

**Comment by emanuelsip** [comment]
> You can try this if you are interested. Linux kernel 6.0+ supported.
> 
> https://github.com/a5a5aa555oo/rtl8188gu

hi, thanks for the response. It was installed with no issues, but it still isn't working
**lsusb**

Bus 001 Device 005: ID 0bda:1a2b Realtek Semiconductor Corp. RTL8188GU 802.11n WLAN Adapter (Driver CDROM Mode)
**ip link show**
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000     link/ether a4:bb:6d:da:f4:af brd ff:ff:ff:ff:ff:ff    altname enp0s31f6
1 

It is mounted as a USB drive, with the Windows driver on it. I guess the issue came from the Driver CDROM detection.

**Comment by dubhater** [comment]
If you install usb_modeswitch it will be switched to wifi mode automatically the next time you plug it in/reboot.

If you want to switch it manually, try the „eject” command.

The wifi drivers will not do it for you.

**Comment by a5a5aa555oo** [comment]
This wifi chip has two mode: Driver CDROM Mode and wifi mode, you have to change it to wifi mode first.
You can use "usb_modeswitch" or "eject" to do that.
