### ISSUE TITLE
谢谢大佬的改版的编译驱动，但我编译安装之后发现还是连不了怎么办？执行操作显示如下(已解决，刚刚发现装上了,我也不知道为啥第一次没装成功orz)

### ISSUE THREAD

**Issue by LeopoldACC** [McMCCRU/rtl8188gu#6]
```
make
```
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.4.0-42-generic/build M=/home/gz/桌面/rtl8188gu-master  modules
make[1]: 进入目录“/usr/src/linux-headers-5.4.0-42-generic”
  Building modules, stage 2.
  MODPOST 1 modules
make[1]: 离开目录“/usr/src/linux-headers-5.4.0-42-generic”

```
sudo make install
```
install -p -m 644 8188gu.ko  /lib/modules/5.4.0-42-generic/kernel/drivers/net/wireless/
/sbin/depmod -a 5.4.0-42-generic

然后我去检查是否安装5.4.0-42-generic到其显示地址时，发现到/lib/modules/5.4.0-42-generic/kernel/drivers/net/wireless/这一层就没有/sbin这个文件夹了

GSM模式也移除了
```
sudo rmmod option
```
rmmod: ERROR: Module option is not currently loaded

我的系统版本是20.04 LTS
麻烦大佬了！

**Comment by wandercn** [comment]
我也遇到8188gu型号驱动问题，自己找资料整理了安装指南.我在Raspberry pi 和 ubuntu 20.0.4都安装成功了。deepin也应该可以。解决了您的问题帮忙点个星星

https://github.com/wandercn/RTL8188GU
